FROM openjdk:11
MAINTAINER pooja
COPY target/urbanclap-serviceDiscovery-0.0.1-SNAPSHOT.jar urbanclap-serviceDiscovery-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/urbanclap-serviceDiscovery-0.0.1-SNAPSHOT.jar"]