FROM openjdk:11
MAINTAINER pooja
COPY target/urbanclap-serviceProvider1-0.0.1-SNAPSHOT.jar urbanclap-serviceProvider1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/urbanclap-serviceProvider1-0.0.1-SNAPSHOT.jar"]